### ISSUE TITLE
假开源，真商业

### ISSUE THREAD

**Issue by mcdull525** [lloves/CloudPhone#1]
假开源你放上来干什么，污染了github环境，推广别搞错地方

**Comment by lloves** [comment]
我们在开放的2、3年时间内，免费支持了很多技术用户的技术咨询。包括webrtc推流技术、GPU直通技术、scrcpy开源代码研究支持，逆向检测分享交流。做了很多努力，帮助云手机社区真正的需求者解决了很多难点。希望多多交流，而不是上来就指责。

**Comment by lloves** [comment]
项目简介页中涉及的单项技术点都可以免费提供咨询、讨论，并给出一些技术方案路线；

关于商业化的的整机方案，需要定制软件、或者使用定制的ROM才需要收费，因为这部分使用不当涉及法律风险问题，没法免费、完全开放提供；
