### ISSUE TITLE
关于开源的问题：Webrtc、Docker/LXC 多开、硬件信息模拟、逆向分析、风控都可以交流

### ISSUE THREAD

**Issue by lloves** [lloves/CloudPhone#4]
- 很多同学问到是否开源的问题，因为无法甄别技术的用途，商业方案完成度在80%左右，开源的风险太高。
- 在过去的2-3年内支持了很多云手机爱好者搭建自己的平台，主要是云手机的改机方法、Webrtc推流技术、虚拟摄像头、虚拟麦克风、逆向技巧等等。
- 希望能继续普及云手机技术，我们愿意分享核心的功能，甚至是Webrtc速率优化、一些大厂的风控核心；

**Comment by galaxy-s10** [comment]
雷电云手机？
